FROM php:8.2-cli

# Installer les extensions système nécessaires
RUN apt-get update && apt-get install -y \
    libzip-dev \
    libicu-dev \
    unzip \
    git \
    curl

# Installer les extensions PHP (pdo_mysql pour la base de données)
RUN docker-php-ext-install pdo pdo_mysql zip intl

# Installer Composer (le gestionnaire de paquets de PHP, indispensable pour Laravel)
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www
